"""mig

Revision ID: bfa736ee7f69
Revises: a80c5ef89b32
Create Date: 2023-01-30 10:50:47.113948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa736ee7f69'
down_revision = 'a80c5ef89b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=True))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
